---
default_stages: [pre-commit]
minimum_pre_commit_version: 3.0.0
default_language_version:
  python: python3.12
repos:
  - repo: local
    hooks:
      - id: pipenv-lock-verify
        name: pipenv-lock-verify
        files: (Pipfile|Pipfile.lock)
        entry: pipenv verify
        pass_filenames: false
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        exclude: .*/(migrations)/.*
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        types_or: [python, ts, tsx, markdown]
        args: [--ignore-words, .codespell-ignore-words]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        exclude: |
          (?x)(
             .*/(migrations)/.*
           )
        args:
          - --no-strict-optional
          - --ignore-missing-imports
          - --config-file=mypy.ini
        additional_dependencies:
          - types-PyYAML
          - types-python-dateutil
          - types-pytz
          - types-freezegun
          - types-requests
          - typing-extensions
