---
services:
  lessons_tracker: &lessons_tracker
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    command: bash -c "granian --interface asgi --host 0.0.0.0 --port 8000 --workers 1 lessons_tracker.asgi:application"
