---
services:
  lessons_tracker: &lessons_tracker
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: bash -c "granian --interface asgi --host 0.0.0.0 --port 8000 --workers 1 lessons_tracker.asgi:application"
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
