---
services:
  lessons_tracker: &lessons_tracker
    build:
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"
    networks:
      - lessons_tracker_network
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - static_data:/lessons_tracker/static
    command: bash -c "gunicorn lessons_tracker.wsgi:application --bind 0.0.0.0:8000 --error-logfile - --access-logfile - --capture-output"
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - lessons_tracker_network

volumes:
  postgres_data:
  static_data:

networks:
  lessons_tracker_network:
