name: Tests

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

jobs:
  tests:
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies

        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
          pipenv install && pipenv install --dev

      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: settings
          DJANGO_DEBUG: false
          DJANGO_SECRET_KEY: "mock-secret-key"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

        run: pipenv run pytest
