# Generated by Django 5.0.4 on 2024-10-23 20:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("6e", "Sixieme"),
                            ("5e", "Cinquieme"),
                            ("4e", "Quatrieme"),
                            ("3e", "Troisieme"),
                            ("2e", "Seconde"),
                            ("1ere", "Premiere"),
                            ("Term", "Terminale"),
                            ("Bac+1", "Bacplus1"),
                            ("Bac+2", "Bacplus2"),
                            ("Bac+3", "Bacplus3"),
                            ("Bac+4", "Bacplus4"),
                            ("Bac+5", "Bacplus5"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "parent_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("address", models.TextField(null=True)),
            ],
        ),
    ]
